// Career Pick — content for secondary pages
(function () {
  const TR = {
    about: {
      hero: { eyebrow: "Hakkımızda", title: ["Herkesin kariyerinde", "doğru hamleyi yapması için"], sub: "Career Pick, kariyer kararlarını tahminden çıkarıp veriye ve net bir plana dayandırma misyonuyla kuruldu." },
      mission: { eyebrow: "Misyonumuz", title: "Kariyer netliğini herkes için erişilebilir kılmak", body: "İnsanların çoğu kariyerinin en kritik kararlarını yeterli rehberlik olmadan veriyor. Biz; yapay zekânın gücünü gerçek piyasa verisiyle birleştirerek, herkesin yanında bir kariyer koçu taşımasını sağlıyoruz — yeni mezunlardan deneyimli profesyonellere kadar." },
      stats: [
        { n: "120K+", l: "analiz edilen CV" },
        { n: "3.400", l: "kariyer rotası" },
        { n: "48", l: "desteklenen sektör" },
        { n: "4.9/5", l: "kullanıcı puanı" },
      ],
      valuesTitle: "Bizi yönlendiren değerler",
      values: [
        { icon: "spark", title: "İnsan önce gelir", body: "Teknoloji araçtır; amaç insanların kariyerinde daha mutlu ve güvende olması." },
        { icon: "check", title: "Net ve dürüst", body: "Boş motivasyon değil; somut, uygulanabilir ve dürüst tavsiyeler veririz." },
        { icon: "route", title: "Veriye dayalı", body: "Her öneri gerçek piyasa verisi ve en iyi pratiklerle desteklenir." },
        { icon: "globe", title: "Herkes için", body: "Hangi aşamada, hangi sektörde olursan ol — kariyer rehberliği bir ayrıcalık olmamalı." },
      ],
      teamTitle: "Ekibimiz",
      teamSub: "Kariyer, yapay zekâ ve tasarım tutkunu küçük ama kararlı bir ekip.",
      team: [
        { name: "Can Aydın", role: "Kurucu & CEO", init: "CA" },
        { name: "Oytun Sezgin", role: "Kurucu & CEO", init: "OS" },
        { name: "Emre Şahin", role: "Yapay Zekâ Mühendisi", init: "EŞ" },
        { name: "Zeynep Aydın", role: "Kariyer Koçu", init: "ZA" },
      ],
      cta: { title: "Yolculuğumuza katıl.", sub: "Career Pick ile kariyerinin kontrolünü ele al.", btn: "Asistanla başla" },
    },
    contact: {
      hero: { eyebrow: "İletişim", title: ["Bizimle", "iletişime geç"], sub: "Sorun, geri bildirimin ya da işbirliği fikrin mi var? Seni dinlemek isteriz." },
      cards: [
        { icon: "globe", title: "Genel sorular", v: "merhaba@careerpick.com" },
        { icon: "spark", title: "Destek", v: "destek@careerpick.com" },
        { icon: "route", title: "İş birliği", v: "ortaklik@careerpick.com" },
      ],
      formTitle: "Mesaj gönder",
      fields: { name: "Adın", email: "E-posta", subject: "Konu", message: "Mesajın", send: "Mesajı gönder", sent: "Teşekkürler! Mesajın alındı (demo)." },
      hours: "Pazartesi–Cuma, 09:00–18:00 (GMT+3) arasında yanıt veriyoruz.",
    },
    careers: {
      hero: { eyebrow: "Kariyer", title: ["Kariyerin geleceğini", "bizimle inşa et"], sub: "İnsanların kariyerini dönüştüren bir ürünü, önemseyen bir ekiple birlikte büyütüyoruz." },
      perksTitle: "Neden Career Pick?",
      perks: [
        { icon: "globe", title: "Uzaktan çalışma", body: "Nereden çalışacağına sen karar ver; esnek saatler." },
        { icon: "spark", title: "Öğrenme bütçesi", body: "Yıllık kişisel gelişim ve eğitim bütçesi." },
        { icon: "check", title: "Sağlık & denge", body: "Özel sağlık sigortası ve gerçek izin kültürü." },
        { icon: "bolt", title: "Erken etki", body: "Küçük ekip, büyük sorumluluk — işin gerçekten önemli." },
      ],
      openTitle: "Açık pozisyonlar",
      jobs: [
        { title: "Kıdemli Frontend Mühendisi", team: "Mühendislik", loc: "Uzaktan · Tam zamanlı" },
        { title: "Yapay Zekâ / ML Mühendisi", team: "Yapay Zekâ", loc: "İstanbul / Uzaktan · Tam zamanlı" },
        { title: "Ürün Tasarımcısı (UX)", team: "Tasarım", loc: "Uzaktan · Tam zamanlı" },
        { title: "Kariyer Koçu", team: "İçerik", loc: "Uzaktan · Yarı zamanlı" },
        { title: "Büyüme Pazarlama Uzmanı", team: "Pazarlama", loc: "İstanbul · Tam zamanlı" },
      ],
      apply: "Başvur",
      cta: { title: "Aradığın rolü göremedin mi?", sub: "Yine de tanışmak isteriz. CV'ni gönder.", btn: "Bize yaz" },
    },
    privacy: {
      hero: { eyebrow: "Gizlilik", title: ["Gizlilik", "politikası"], sub: "Verilerine saygı duyuyoruz. Bu politika hangi verileri, neden ve nasıl işlediğimizi açıklar." },
      updated: "Son güncelleme: 1 Haziran 2026",
      sections: [
        { h: "Hangi verileri topluyoruz?", p: "Hesap bilgilerin (ad, e-posta), asistana sağladığın CV ve sohbet içerikleri ile hizmeti iyileştirmek için temel kullanım verileri. Hassas verileri paylaşmaman önerilir." },
        { h: "Verilerini neden işliyoruz?", p: "Verilerin yalnızca sana özel kariyer önerileri üretmek, hizmeti sağlamak ve geliştirmek için kullanılır. Reklam amaçlı üçüncü taraflarla paylaşılmaz." },
        { h: "Yapay zekâ ve içeriğin", p: "CV ve sohbet içeriğin öneri üretmek için yapay zekâ modelleri tarafından işlenir. İçeriğini dilediğin zaman silebilirsin." },
        { h: "Verilerini saklama süresi", p: "Verilerini hesabın aktif olduğu sürece saklarız. Hesabını sildiğinde ilişkili verilerin makul bir süre içinde kaldırılır." },
        { h: "Haklarına", p: "Verilerine erişme, düzeltme, silme ve taşıma hakkın vardır. Bu hakları kullanmak için bizimle iletişime geçebilirsin." },
        { h: "Güvenlik", p: "Verilerini sektör standardı şifreleme ve erişim kontrolleriyle koruruz. Yine de internet üzerinden hiçbir aktarım %100 güvenli değildir." },
        { h: "İletişim", p: "Gizlilikle ilgili sorular için gizlilik@careerpick.com adresinden bize ulaşabilirsin." },
      ],
    },
    blog: {
      hero: { eyebrow: "Blog", title: ["Kariyer içgörüleri", "ve rehberler"], sub: "Kariyer planlama, CV, mülakat ve beceri geliştirme üzerine pratik yazılar." },
      featuredTag: "Öne çıkan",
      posts: [
        { tag: "Kariyer rotası", title: "2026'da en çok aranan 10 dijital beceri", excerpt: "Piyasa verilerine göre önümüzdeki yıl en değerli olacak beceriler ve bunları nasıl öğreneceğin.", date: "3 Haz 2026", read: "6 dk", featured: true },
        { tag: "CV", title: "ATS dostu CV nasıl yazılır?", excerpt: "İşe alım sistemlerini geçen, insan gözünü de etkileyen bir CV için adım adım rehber.", date: "28 May 2026", read: "5 dk" },
        { tag: "Mülakat", title: "Davranışsal mülakat sorularına STAR ile cevap", excerpt: "STAR yöntemiyle hikâyeni etkili biçimde anlatmanın formülü.", date: "21 May 2026", read: "7 dk" },
        { tag: "Kariyer değişimi", title: "Sektör değiştirirken transfer edilebilir beceriler", excerpt: "Mevcut deneyimini yeni bir alana taşımanın akıllı yolları.", date: "14 May 2026", read: "6 dk" },
        { tag: "Maaş", title: "Maaş müzakeresinde 5 yaygın hata", excerpt: "Çoğu adayın masada para kaybetmesine neden olan tuzaklar ve çözümleri.", date: "7 May 2026", read: "4 dk" },
        { tag: "Gelişim", title: "Haftada 5 saatle yeni bir beceri öğrenmek", excerpt: "Yoğun bir programda sürdürülebilir öğrenme planı kurmanın yolu.", date: "30 Nis 2026", read: "5 dk" },
      ],
      readMore: "Oku",
    },
    guide: {
      hero: { eyebrow: "Kariyer Rehberi", title: ["Kariyerini adım adım", "planlamak için rehber"], sub: "Nereden başlayacağını bilmiyorsan doğru yerdesin. Aşamalara göre derlenmiş kapsamlı rehberler." },
      catsTitle: "Konuya göre keşfet",
      categories: [
        { icon: "route", title: "Kariyer planlama", count: "12 rehber", body: "Hedef belirleme, kariyer rotası çıkarma ve karar verme." },
        { icon: "doc", title: "CV & başvuru", count: "9 rehber", body: "Etkili CV, ön yazı ve LinkedIn profili oluşturma." },
        { icon: "spark", title: "Beceri geliştirme", count: "8 rehber", body: "Beceri boşluğunu kapatma ve öğrenme planı kurma." },
        { icon: "bolt", title: "Mülakat", count: "7 rehber", body: "Hazırlık, sık sorulan sorular ve özgüven." },
        { icon: "globe", title: "Kariyer değişimi", count: "6 rehber", body: "Sektör değiştirme ve transfer edilebilir beceriler." },
        { icon: "check", title: "Maaş & müzakere", count: "5 rehber", body: "Maaş araştırması ve etkili müzakere taktikleri." },
      ],
      stepsTitle: "Yeni başlıyorsan",
      steps: [
        { n: "01", title: "Kendini tanı", body: "Güçlü yönlerini, ilgi alanlarını ve değerlerini netleştir." },
        { n: "02", title: "Hedef belirle", body: "Ulaşmak istediğin rolü ve zaman çizelgeni tanımla." },
        { n: "03", title: "Plan yap", body: "Beceri boşluğunu kapatacak somut bir öğrenme planı kur." },
        { n: "04", title: "Harekete geç", body: "Başvur, ağ kur ve ilerlemeni düzenli takip et." },
      ],
      cta: { title: "Kişisel rehberini asistandan al.", sub: "Rehberleri okumakla kalma — sana özel bir plan çıkar.", btn: "Asistanla başla" },
    },
    templates: {
      hero: { eyebrow: "CV Şablonları", title: ["Profesyonel ve", "ATS dostu CV şablonları"], sub: "Ücretsiz indir, kendine göre düzenle ve asistana analiz ettir. Her sektöre uygun tasarımlar." },
      filtersLabel: "Kategoriler",
      filters: ["Tümü", "Modern", "Klasik", "Yaratıcı", "Yeni mezun", "Teknik"],
      items: [
        { name: "Aurora", cat: "Modern", tone: "a", desc: "İki sütunlu, temiz ve çağdaş." },
        { name: "Klasik Pro", cat: "Klasik", tone: "b", desc: "Tek sütun, kurumsal ve sade." },
        { name: "Spektrum", cat: "Yaratıcı", tone: "c", desc: "Renk vurgulu, portfolyo dostu." },
        { name: "İlk Adım", cat: "Yeni mezun", tone: "d", desc: "Deneyim yerine beceri ve projeler." },
        { name: "Devlog", cat: "Teknik", tone: "a", desc: "Yazılımcılar için teknik beceri odaklı." },
        { name: "Minimal", cat: "Modern", tone: "b", desc: "Bol beyaz alan, tipografi odaklı." },
        { name: "Eskiz", cat: "Yaratıcı", tone: "c", desc: "Tasarımcılar için cesur düzen." },
        { name: "Akademi", cat: "Klasik", tone: "d", desc: "Akademik ve araştırma CV'leri için." },
      ],
      use: "İndir",
      preview: "Önizle",
      cta: { title: "CV'ni şablona döktün mü?", sub: "Asistana yükle, saniyeler içinde güçlendirelim.", btn: "CV'mi analiz et" },
    },
  };

  const EN = {
    about: {
      hero: { eyebrow: "About us", title: ["So everyone can make", "the right career move"], sub: "Career Pick was founded to take career decisions out of guesswork and ground them in data and a clear plan." },
      mission: { eyebrow: "Our mission", title: "Make career clarity accessible to everyone", body: "Most people make their most important career decisions without enough guidance. We combine the power of AI with real market data so everyone can carry a career coach with them — from new grads to experienced professionals." },
      stats: [
        { n: "120K+", l: "resumes analyzed" },
        { n: "3,400", l: "career paths" },
        { n: "48", l: "industries supported" },
        { n: "4.9/5", l: "user rating" },
      ],
      valuesTitle: "The values that guide us",
      values: [
        { icon: "spark", title: "People first", body: "Technology is a tool; the goal is people feeling happier and safer in their careers." },
        { icon: "check", title: "Clear and honest", body: "Not empty motivation — concrete, actionable and honest advice." },
        { icon: "route", title: "Data-driven", body: "Every recommendation is backed by real market data and best practices." },
        { icon: "globe", title: "For everyone", body: "Whatever your stage or industry — career guidance shouldn't be a privilege." },
      ],
      teamTitle: "Our team",
      teamSub: "A small but determined team passionate about careers, AI and design.",
      team: [
        { name: "Can Aydın", role: "Founder & CEO", init: "CA" },
        { name: "Oytun Sezgin", role: "Founder & CEO", init: "OS" },
        { name: "Emre Şahin", role: "AI Engineer", init: "EŞ" },
        { name: "Zeynep Aydın", role: "Career Coach", init: "ZA" },
      ],
      cta: { title: "Join our journey.", sub: "Take control of your career with Career Pick.", btn: "Start with the assistant" },
    },
    contact: {
      hero: { eyebrow: "Contact", title: ["Get in", "touch with us"], sub: "Have a question, feedback or a collaboration idea? We'd love to hear from you." },
      cards: [
        { icon: "globe", title: "General", v: "hello@careerpick.com" },
        { icon: "spark", title: "Support", v: "support@careerpick.com" },
        { icon: "route", title: "Partnerships", v: "partners@careerpick.com" },
      ],
      formTitle: "Send a message",
      fields: { name: "Your name", email: "Email", subject: "Subject", message: "Your message", send: "Send message", sent: "Thanks! Your message was received (demo)." },
      hours: "We reply Monday–Friday, 9am–6pm (GMT+3).",
    },
    careers: {
      hero: { eyebrow: "Careers", title: ["Build the future", "of careers with us"], sub: "We're growing a product that transforms people's careers, with a team that genuinely cares." },
      perksTitle: "Why Career Pick?",
      perks: [
        { icon: "globe", title: "Remote-first", body: "You decide where you work; flexible hours." },
        { icon: "spark", title: "Learning budget", body: "Annual personal growth and education budget." },
        { icon: "check", title: "Health & balance", body: "Private health insurance and a real time-off culture." },
        { icon: "bolt", title: "Early impact", body: "Small team, big ownership — your work truly matters." },
      ],
      openTitle: "Open positions",
      jobs: [
        { title: "Senior Frontend Engineer", team: "Engineering", loc: "Remote · Full-time" },
        { title: "AI / ML Engineer", team: "AI", loc: "Istanbul / Remote · Full-time" },
        { title: "Product Designer (UX)", team: "Design", loc: "Remote · Full-time" },
        { title: "Career Coach", team: "Content", loc: "Remote · Part-time" },
        { title: "Growth Marketer", team: "Marketing", loc: "Istanbul · Full-time" },
      ],
      apply: "Apply",
      cta: { title: "Didn't see your role?", sub: "We'd still love to meet you. Send us your resume.", btn: "Write to us" },
    },
    privacy: {
      hero: { eyebrow: "Privacy", title: ["Privacy", "policy"], sub: "We respect your data. This policy explains what data we process, why and how." },
      updated: "Last updated: June 1, 2026",
      sections: [
        { h: "What data we collect", p: "Your account info (name, email), the resume and chat content you provide to the assistant, and basic usage data to improve the service. We recommend not sharing sensitive data." },
        { h: "Why we process your data", p: "Your data is used only to generate personalized career recommendations, provide and improve the service. It is not shared with third parties for advertising." },
        { h: "AI and your content", p: "Your resume and chat content are processed by AI models to generate recommendations. You can delete your content at any time." },
        { h: "Data retention", p: "We keep your data while your account is active. When you delete your account, your associated data is removed within a reasonable period." },
        { h: "Your rights", p: "You have the right to access, correct, delete and port your data. Contact us to exercise these rights." },
        { h: "Security", p: "We protect your data with industry-standard encryption and access controls. Still, no transmission over the internet is 100% secure." },
        { h: "Contact", p: "For privacy questions, reach us at privacy@careerpick.com." },
      ],
    },
    blog: {
      hero: { eyebrow: "Blog", title: ["Career insights", "and guides"], sub: "Practical writing on career planning, resumes, interviews and skill building." },
      featuredTag: "Featured",
      posts: [
        { tag: "Career path", title: "The 10 most in-demand digital skills in 2026", excerpt: "The skills the market will value most next year and how to learn them.", date: "Jun 3, 2026", read: "6 min", featured: true },
        { tag: "Resume", title: "How to write an ATS-friendly resume", excerpt: "A step-by-step guide to a resume that passes screening systems and impresses humans.", date: "May 28, 2026", read: "5 min" },
        { tag: "Interview", title: "Answering behavioral questions with STAR", excerpt: "The formula for telling your story effectively with the STAR method.", date: "May 21, 2026", read: "7 min" },
        { tag: "Career change", title: "Transferable skills when switching industries", excerpt: "Smart ways to carry your experience into a new field.", date: "May 14, 2026", read: "6 min" },
        { tag: "Salary", title: "5 common mistakes in salary negotiation", excerpt: "The traps that cost most candidates money at the table — and how to avoid them.", date: "May 7, 2026", read: "4 min" },
        { tag: "Growth", title: "Learning a new skill in 5 hours a week", excerpt: "How to build a sustainable learning plan in a busy schedule.", date: "Apr 30, 2026", read: "5 min" },
      ],
      readMore: "Read",
    },
    guide: {
      hero: { eyebrow: "Career guide", title: ["A guide to plan your", "career step by step"], sub: "If you don't know where to start, you're in the right place. Comprehensive guides organized by stage." },
      catsTitle: "Explore by topic",
      categories: [
        { icon: "route", title: "Career planning", count: "12 guides", body: "Goal setting, mapping a career path and decision making." },
        { icon: "doc", title: "Resume & applying", count: "9 guides", body: "Building an effective resume, cover letter and LinkedIn profile." },
        { icon: "spark", title: "Skill building", count: "8 guides", body: "Closing skill gaps and building a learning plan." },
        { icon: "bolt", title: "Interview", count: "7 guides", body: "Preparation, common questions and confidence." },
        { icon: "globe", title: "Career change", count: "6 guides", body: "Switching industries and transferable skills." },
        { icon: "check", title: "Salary & negotiation", count: "5 guides", body: "Salary research and effective negotiation tactics." },
      ],
      stepsTitle: "If you're just starting",
      steps: [
        { n: "01", title: "Know yourself", body: "Clarify your strengths, interests and values." },
        { n: "02", title: "Set a goal", body: "Define the role you want and your timeline." },
        { n: "03", title: "Make a plan", body: "Build a concrete learning plan to close your skill gap." },
        { n: "04", title: "Take action", body: "Apply, network and track your progress regularly." },
      ],
      cta: { title: "Get your personal guide from the assistant.", sub: "Don't just read guides — get a plan made for you.", btn: "Start with the assistant" },
    },
    templates: {
      hero: { eyebrow: "Resume templates", title: ["Professional and", "ATS-friendly resume templates"], sub: "Download free, customize and have the assistant analyze it. Designs for every industry." },
      filtersLabel: "Categories",
      filters: ["All", "Modern", "Classic", "Creative", "New grad", "Technical"],
      items: [
        { name: "Aurora", cat: "Modern", tone: "a", desc: "Two-column, clean and contemporary." },
        { name: "Classic Pro", cat: "Classic", tone: "b", desc: "Single column, corporate and simple." },
        { name: "Spectrum", cat: "Creative", tone: "c", desc: "Color-accented, portfolio-friendly." },
        { name: "First Step", cat: "New grad", tone: "d", desc: "Skills and projects over experience." },
        { name: "Devlog", cat: "Technical", tone: "a", desc: "Technical-skill focused for engineers." },
        { name: "Minimal", cat: "Modern", tone: "b", desc: "Lots of whitespace, typography-led." },
        { name: "Sketch", cat: "Creative", tone: "c", desc: "Bold layout for designers." },
        { name: "Academy", cat: "Classic", tone: "d", desc: "For academic and research CVs." },
      ],
      use: "Download",
      preview: "Preview",
      cta: { title: "Put your resume into a template?", sub: "Upload it to the assistant and we'll strengthen it in seconds.", btn: "Analyze my resume" },
    },
  };

  if (window.CP_CONTENT) {
    Object.assign(window.CP_CONTENT.tr.pages, TR);
    Object.assign(window.CP_CONTENT.en.pages, EN);
  }
})();
