/* Profil sayfasi metinleri — ogrenme plani */
window.CP_PROFIL = {
  tr: {
    brand: "Career Pick",
    title: "Öğrenme planım",
    subtitle: "Önerilen eğitimlerini takip et, başla ve tamamla.",
    loginPrompt: "Eğitim planını görmek için Gmail ile giriş yap.",
    loginBtn: "Gmail ile giriş",
    logoutBtn: "Çıkış",
    chatBtn: "Kariyer Sohbeti",
    overall: "Genel ilerleme",
    empty: "Henüz önerilen eğitim yok. Kariyer Sohbetini tamamla.",
    status: {
      tamamlandi: "Tamamlandı",
      devam_ediyor: "Devam ediyor",
      eksik: "Başlanmadı",
    },
    openTraining: "Eğitime git",
    markStarted: "Başlattım",
    markCompleted: "Bitirdim",
    noLink: "Bu eğitim için dış link yok",
    weekTitle: "Bu hafta yapman gerekenler",
    weekEmpty: "Harika — bu hafta bekleyen bir aksiyon yok.",
    weekContinue: "Devam et",
    weekStart: "Başlamayı unutma",
    weekCongrats: "Tebrikler, tamamladın",
    nextTitle: "Sıradaki önerin",
    remindersTitle: "Haftalık e-posta hatırlatması",
    remindersHint: "Devam eden veya başlamadığın eğitimler için haftada en fazla bir özet mail. Varsayılan kapalı.",
    remindersOn: "Açık",
    remindersOff: "Kapalı",
    startedAt: "Başlangıç",
    completedAt: "Bitiş",
    loading: "Yükleniyor…",
    notConfigured: "Supabase yapılandırması eksik. Ortam değişkenlerini kontrol et.",
  },
  en: {
    brand: "Career Pick",
    title: "My learning plan",
    subtitle: "Track recommended courses — start, continue, finish.",
    loginPrompt: "Sign in with Gmail to see your learning plan.",
    loginBtn: "Sign in with Gmail",
    logoutBtn: "Sign out",
    chatBtn: "Career Chat",
    overall: "Overall progress",
    empty: "No recommended trainings yet. Complete Career Chat.",
    status: {
      tamamlandi: "Completed",
      devam_ediyor: "In progress",
      eksik: "Not started",
    },
    openTraining: "Open course",
    markStarted: "I started",
    markCompleted: "I finished",
    noLink: "No external link for this course",
    weekTitle: "This week’s actions",
    weekEmpty: "Nice — nothing waiting this week.",
    weekContinue: "Keep going",
    weekStart: "Don’t forget to start",
    weekCongrats: "Congrats, you finished",
    nextTitle: "Up next",
    remindersTitle: "Weekly email reminders",
    remindersHint: "At most one digest per week for in-progress or not-started courses. Off by default.",
    remindersOn: "On",
    remindersOff: "Off",
    startedAt: "Started",
    completedAt: "Completed",
    loading: "Loading…",
    notConfigured: "Supabase is not configured. Check environment variables.",
  },
};
