/* Profil sayfasi metinleri — ogrenme plani + yol haritasi */
window.CP_PROFIL = {
  tr: {
    brand: "Career Pick",
    title: "Öğrenme planım",
    subtitle: "Bugün ne yapacağını gör; yol, pratik ve keşif ayrı sayfalarda.",
    pageTitle: {
      bugun: "Bugün",
      yol: "Yolum",
      pratik: "Pratikler",
      kesfet: "Keşif",
    },
    pageSubtitle: {
      bugun: "Ne yapacağını bir bakışta gör.",
      yol: "Yol haritan ve eğitimlerin.",
      pratik: "Check-in ve kısa pratikler — haftalık döngü.",
      kesfet: "Rolün, yatay geçişler ve sektör notları.",
    },
    loginPrompt: "Eğitim planını görmek için Gmail ile giriş yap.",
    loginBtn: "Gmail ile giriş",
    logoutBtn: "Çıkış",
    chatBtn: "Kariyer Sohbeti",
    jobFitBtn: "İlan uyumu",
    tabs: {
      bugun: "Bugün",
      yol: "Yolum",
      pratik: "Pratikler",
      kesfet: "Keşif",
    },
    tabAria: "Profil sayfaları",
    goRoadmap: "Yol haritana git",
    goPratik: "Pratiklere git",
    loopAria: "Pratik döngüsü",
    loopMicro: (done, total) => `Bu hafta ${done}/${total} pratik`,
    loopMicroEmpty: "Bu hafta henüz pratik yok",
    loopMicroNeedChat: "Pratikler için önce sohbeti tamamla",
    loopCheckinTodo: "Check-in yap",
    loopCheckinDone: "Check-in tamam",
    loopGo: "Aç",
    loopNudgeCheckin: "Pratikler bitti — check-in yap",
    loopNudgeMicro: "Kalan pratiklere geç",
    hubHello: "Merhaba",
    hubHelloNamed: (n) => "Merhaba, " + n,
    hubStatusDraft: "Yarıda kalan sohbetin var — kaldığın yerden devam et.",
    hubStatusStep: (label, title) =>
      "Aktif adımın: " + (label || "") + (title ? (" — " + title) : ""),
    hubStatusGoal: (g) => "Hedefin: " + g,
    hubStatusStart: "Planın henüz yok — Kariyer Sohbetini tamamla.",
    hubStatusClear: "Bu hafta bekleyen bir aksiyon yok.",
    hubStatusEmpty: "Bugün ne yapacağını burada göreceksin.",
    hubCtaResume: "Devam et",
    hubCtaContinue: "Devam et",
    hubCtaStart: "Başla",
    hubCtaPath: "Yolum",
    hubCtaChat: "Sohbet",
    hubWeekMore: "Yol haritasında gör",
    accountSummary: "Hesap ve tercihler",
    onboardTitle: "Başlamak için",
    onboardLead: "Önce sohbet → yol oluşur",
    onboardStep1: "Kariyer Sohbetini tamamla",
    onboardStep2: "Yol haritan ve eğitimlerin oluşur",
    onboardStep3: "Haftalık pratiklere ve check-in’e geç",
    onboardCta: "Sohbete başla",
    overall: "Genel ilerleme",
    empty: "Henüz eğitim yok — Kariyer Sohbetini tamamla.",
    goalTitle: "Kariyer hedefin",
    currentRoleTitle: "Bugünkü rolün",
    currentRoleHint: "İsteğe bağlı — farklı bir uzmanlık alanı keşfetmek istersen yaz.",
    currentRolePlaceholder: "Örn. satış temsilcisi, yazılımcı, öğretmen…",
    currentRoleSave: "Kaydet",
    exploreTitle: "Sıkıştın mı?",
    exploreHint: "Mevcut yolunu bırakmak zorunda değilsin. Bazı roller yakın uzmanlıklara da kapı açabilir — keşfetmek istersen bak.",
    exploreNote: "Bunlar kesin geçiş yolları değil; gerekçeye dayalı olasılıklar.",
    compareSummaryTitle: "Yetkinlik gelişimi",
    compareSummaryText: (up, down) =>
      `${up} alanda ilerleme sinyali, ${down} alanda bu turda daha yumuşak bir sinyal. Yaklaşık bir karşılaştırma.`,
    compareSummaryNone: "İkinci sohbette karşılaştırma açılır.",
    compareSummaryFirst: "İlk ölçüm kaydedildi.",
    roadmapTitle: "Yol haritan",
    stepProgress: "Adım",
    stepStatus: {
      bekliyor: "Bekliyor",
      aktif: "Aktif",
      bitti: "Bitti",
    },
    noResources: "Henüz kaynak yok",
    otherTrainings: "Diğer eğitimler",
    status: {
      tamamlandi: "Tamamlandı",
      devam_ediyor: "Devam ediyor",
      eksik: "Başlanmadı",
    },
    openTraining: "Eğitime git",
    markStarted: "Başlattım",
    markCompleted: "Bitirdim",
    noLink: "Bu eğitim için dış link yok",
    weekTitle: "Bu hafta yapman gerekenler",
    weekActiveStep: "Aktif adımın:",
    weekEmpty: "Harika — bu hafta bekleyen bir aksiyon yok.",
    weekContinue: "Devam et",
    weekStart: "Başlamayı unutma",
    weekCongrats: "Tebrikler, tamamladın",
    nextTitle: "Sıradaki önerin",
    microTitle: "Bu haftanın pratikleri",
    microHint: "Zayıf yetkinliklerin için 10–30 dk’lık kısa iş-yaşam pratikleri. Yaklaşık gelişim sinyali — kesin bilimsel ölçüm değil.",
    microEmptyChat: "Önce Kariyer Sohbetini tamamla.",
    microEmptyChatCta: "Sohbete git",
    microEmptyWeek: "Bu hafta için henüz pratik yok.",
    microDone: "Yaptım",
    microDoneLabel: "Yapıldı",
    microDue: "Öneri gün",
    sectorNotesTitle: "Sektör notların",
    sectorNotesHint: "3–5 dakikalık mentör notları — blog değil, üründe kısa rehberlik. Maaş veya tarih garantisi içermez.",
    sectorNotesEmpty: "Sohbette sektör yazınca burada notlar görünür.",
    sectorNotesSector: (key) => (key === "genel" ? "Genel kariyer" : ("Sektör: " + key)),
    sectorCta: {
      micro_task: "İlgili pratiğe git",
      chat: "Sohbete dön",
      training: "Eğitime git",
    },
    draftResumeTitle: "Yarıda kalan sohbetin var",
    draftResumeLink: "Devam et",
    planFree: "Free",
    planPlus: "Plus",
    chatsLeft: "Kalan sohbet",
    cancelPlus: "Aboneliği iptal et",
    upgradePlus: "Plus’a geç",
    cancelConfirm: "Plus aboneliğini iptal etmek istiyor musun? Dönem sonunda veya hemen Free’ye dönebilirsin; profilin açık kalır.",
    cancelDone: "Abonelik iptal edildi. Plan Free.",
    cancelFail: "İptal başarısız. Biraz sonra tekrar dene.",
    billingPlusOk: "Career Pick Plus aktif — ekstra sohbet turların açıldı.",
    checkinTitle: "Haftalık check-in",
    checkinHint: "1–2 kısa soru. Zorunlu değil — yazdığın not yalnızca sana ait.",
    checkinQ1: "Bu hafta kariyerinde somut olarak ne yaptın veya öğrendin?",
    checkinQ2: "Gelecek hafta tek önceliğin ne? (opsiyonel)",
    checkinChoiceLabel: "Odak (opsiyonel)",
    checkinChoices: {
      egitim: "Eğitim",
      pratik: "Pratik",
      basvuru: "Başvuru",
      belirsiz: "Henüz net değil",
    },
    checkinSave: "Kaydet",
    checkinEdit: "Düzenle",
    checkinCancel: "Vazgeç",
    checkinEmpty: "Bu hafta henüz check-in yok.",
    checkinHistory: "Son haftalar",
    checkinHistoryEmpty: "Geçmiş yok.",
    checkinNeedQ1: "Birinci soruya kısa bir cevap yaz.",
    shareCardBtn: "Özet kartı",
    shareCard: {
      title: "Özet kartı",
      close: "Kapat",
      loading: "Hazırlanıyor…",
      empty: "Önce Kariyer Sohbetini tamamla — yetkinlik veya yol haritası gerekli.",
      showName: "İsmimi kartta göster (varsayılan kapalı)",
      hint: "PNG’yi LinkedIn’e görsel olarak yükleyebilir veya metni gönderiye yapıştırabilirsin. Otomatik paylaşım yok.",
      downloadPng: "PNG indir",
      copyText: "Metni kopyala",
      createLink: "Public link oluştur",
      downloaded: "PNG indirildi",
      downloadError: "İndirme başarısız",
      copied: "Metin kopyalandı",
      copyError: "Kopyalanamadı",
      linkReady: "Public link kopyalandı",
      linkError: "Link oluşturulamadı — share_cards migration gerekir",
    },
    remindersTitle: "Haftalık e-posta hatırlatması",
    remindersHint: "Yol haritan, eğitimlerin ve pratiklerin için haftada en fazla bir özet mail. Varsayılan kapalı.",
    remindersOn: "Açık",
    remindersOff: "Kapalı",
    startedAt: "Başlangıç",
    completedAt: "Bitiş",
    loading: "Yükleniyor…",
    notConfigured: "Supabase yapılandırması eksik. Ortam değişkenlerini kontrol et.",
  },
  en: {
    brand: "Career Pick",
    title: "My learning plan",
    subtitle: "See what to do today — path, practices, and explore live on separate pages.",
    pageTitle: {
      bugun: "Today",
      yol: "Path",
      pratik: "Practices",
      kesfet: "Explore",
    },
    pageSubtitle: {
      bugun: "See what to do at a glance.",
      yol: "Your roadmap and courses.",
      pratik: "Check-in and short practices — your weekly loop.",
      kesfet: "Your role, adjacent paths, and sector notes.",
    },
    loginPrompt: "Sign in with Gmail to see your learning plan.",
    loginBtn: "Sign in with Gmail",
    logoutBtn: "Sign out",
    chatBtn: "Career Chat",
    jobFitBtn: "Job fit",
    tabs: {
      bugun: "Today",
      yol: "Path",
      pratik: "Practices",
      kesfet: "Explore",
    },
    tabAria: "Profile pages",
    goRoadmap: "Go to your roadmap",
    goPratik: "Go to practices",
    loopAria: "Practice loop",
    loopMicro: (done, total) => `This week ${done}/${total} practices`,
    loopMicroEmpty: "No practices this week yet",
    loopMicroNeedChat: "Complete Career Chat first for practices",
    loopCheckinTodo: "Do check-in",
    loopCheckinDone: "Check-in done",
    loopGo: "Open",
    loopNudgeCheckin: "Practices done — do check-in",
    loopNudgeMicro: "Go to remaining practices",
    hubHello: "Hello",
    hubHelloNamed: (n) => "Hello, " + n,
    hubStatusDraft: "You have an unfinished chat — pick up where you left off.",
    hubStatusStep: (label, title) =>
      "Active step: " + (label || "") + (title ? (" — " + title) : ""),
    hubStatusGoal: (g) => "Your goal: " + g,
    hubStatusStart: "No plan yet — complete Career Chat.",
    hubStatusClear: "Nothing waiting this week.",
    hubStatusEmpty: "You’ll see what to do today here.",
    hubCtaResume: "Continue",
    hubCtaContinue: "Continue",
    hubCtaStart: "Start",
    hubCtaPath: "Path",
    hubCtaChat: "Chat",
    hubWeekMore: "See on roadmap",
    accountSummary: "Account & preferences",
    onboardTitle: "Get started",
    onboardLead: "Chat first → your path appears",
    onboardStep1: "Complete Career Chat",
    onboardStep2: "Your roadmap and courses are created",
    onboardStep3: "Move into weekly practices and check-in",
    onboardCta: "Start chat",
    overall: "Overall progress",
    empty: "No courses yet — complete Career Chat.",
    goalTitle: "Your career goal",
    currentRoleTitle: "Your current role",
    currentRoleHint: "Optional — add it if you want to explore adjacent specialties.",
    currentRolePlaceholder: "e.g. sales rep, software engineer, teacher…",
    currentRoleSave: "Save",
    exploreTitle: "Feeling stuck?",
    exploreHint: "You don’t have to leave your path. Some roles also open doors to nearby specialties — explore if you like.",
    exploreNote: "These aren’t guaranteed moves — just rationale-based possibilities.",
    compareSummaryTitle: "Competency progress",
    compareSummaryText: (up, down) =>
      `Progress signal in ${up} area(s); a softer signal in ${down}. Approximate comparison only.`,
    compareSummaryNone: "Comparison unlocks on a second chat.",
    compareSummaryFirst: "First measurement saved.",
    roadmapTitle: "Your roadmap",
    stepProgress: "Step",
    stepStatus: {
      bekliyor: "Waiting",
      aktif: "Active",
      bitti: "Done",
    },
    noResources: "No resources yet",
    otherTrainings: "Other courses",
    status: {
      tamamlandi: "Completed",
      devam_ediyor: "In progress",
      eksik: "Not started",
    },
    openTraining: "Open course",
    markStarted: "I started",
    markCompleted: "I finished",
    noLink: "No external link for this course",
    weekTitle: "This week’s actions",
    weekActiveStep: "Your active step:",
    weekEmpty: "Nice — nothing waiting this week.",
    weekContinue: "Keep going",
    weekStart: "Don’t forget to start",
    weekCongrats: "Congrats, you finished",
    nextTitle: "Up next",
    microTitle: "This week’s practices",
    microHint: "Short 10–30 min work-life drills for weaker competencies. An approximate growth signal — not a scientific measurement.",
    microEmptyChat: "Complete Career Chat first.",
    microEmptyChatCta: "Go to chat",
    microEmptyWeek: "No practices for this week yet.",
    microDone: "Done",
    microDoneLabel: "Completed",
    microDue: "Suggested day",
    sectorNotesTitle: "Your sector notes",
    sectorNotesHint: "3–5 minute mentor notes — in-product guidance, not a blog. No salary or date guarantees.",
    sectorNotesEmpty: "Notes appear after you name a sector in chat.",
    sectorNotesSector: (key) => (key === "genel" ? "General career" : ("Sector: " + key)),
    sectorCta: {
      micro_task: "Go to related practice",
      chat: "Back to chat",
      training: "Go to courses",
    },
    draftResumeTitle: "You have an unfinished chat",
    draftResumeLink: "Continue",
    planFree: "Free",
    planPlus: "Plus",
    chatsLeft: "Chats left",
    cancelPlus: "Cancel subscription",
    upgradePlus: "Go Plus",
    cancelConfirm: "Cancel Career Pick Plus? Your profile stays open; plan returns to Free.",
    cancelDone: "Subscription canceled. Plan is Free.",
    cancelFail: "Cancel failed. Try again shortly.",
    billingPlusOk: "Career Pick Plus is active — extra chats unlocked.",
    checkinTitle: "Weekly check-in",
    checkinHint: "1–2 short questions. Optional — your note stays private to you.",
    checkinQ1: "What did you concretely do or learn for your career this week?",
    checkinQ2: "What’s your single priority next week? (optional)",
    checkinChoiceLabel: "Focus (optional)",
    checkinChoices: {
      egitim: "Learning",
      pratik: "Practice",
      basvuru: "Applications",
      belirsiz: "Not sure yet",
    },
    checkinSave: "Save",
    checkinEdit: "Edit",
    checkinCancel: "Cancel",
    checkinEmpty: "No check-in this week yet.",
    checkinHistory: "Recent weeks",
    checkinHistoryEmpty: "No history yet.",
    checkinNeedQ1: "Please write a short answer to the first question.",
    shareCardBtn: "Summary card",
    shareCard: {
      title: "Summary card",
      close: "Close",
      loading: "Preparing…",
      empty: "Complete Career Chat first — competencies or a roadmap are required.",
      showName: "Show my name on the card (off by default)",
      hint: "Upload the PNG to LinkedIn or paste the text into a post. No auto-posting.",
      downloadPng: "Download PNG",
      copyText: "Copy text",
      createLink: "Create public link",
      downloaded: "PNG downloaded",
      downloadError: "Download failed",
      copied: "Text copied",
      copyError: "Could not copy",
      linkReady: "Public link copied",
      linkError: "Could not create link — run share_cards migration",
    },
    remindersTitle: "Weekly email reminders",
    remindersHint: "At most one digest per week about your roadmap, courses, and practices. Off by default.",
    remindersOn: "On",
    remindersOff: "Off",
    startedAt: "Started",
    completedAt: "Completed",
    loading: "Loading…",
    notConfigured: "Supabase is not configured. Check environment variables.",
  },
};
