/* Profil sayfasi metinleri — ogrenme plani + yol haritasi */
window.CP_PROFIL = {
  tr: {
    brand: "Career Pick",
    title: "Öğrenme planım",
    subtitle: "Hedefine giden yol haritasını takip et; eğitimlere başla ve tamamla.",
    loginPrompt: "Eğitim planını görmek için Gmail ile giriş yap.",
    loginBtn: "Gmail ile giriş",
    logoutBtn: "Çıkış",
    chatBtn: "Kariyer Sohbeti",
    jobFitBtn: "İlan uyumu",
    overall: "Genel ilerleme",
    empty: "Henüz önerilen eğitim yok. Kariyer Sohbetini tamamla.",
    goalTitle: "Kariyer hedefin",
    compareSummaryTitle: "Yetkinlik gelişimi",
    compareSummaryText: (up, down) =>
      `${up} alanda ilerleme sinyali, ${down} alanda bu turda daha yumuşak bir sinyal. Yaklaşık bir karşılaştırma.`,
    compareSummaryNone: "Henüz karşılaştırma yok. Kariyer Sohbetini ikinci kez tamamlayınca burada özet görünür.",
    compareSummaryFirst: "İlk ölçüm kaydedildi. İkinci sohbette karşılaştırma açılır.",
    roadmapTitle: "Yol haritan",
    stepProgress: "Adım",
    stepStatus: {
      bekliyor: "Bekliyor",
      aktif: "Aktif",
      bitti: "Bitti",
    },
    noResources: "Henüz kaynak yok",
    otherTrainings: "Diğer eğitimler",
    status: {
      tamamlandi: "Tamamlandı",
      devam_ediyor: "Devam ediyor",
      eksik: "Başlanmadı",
    },
    openTraining: "Eğitime git",
    markStarted: "Başlattım",
    markCompleted: "Bitirdim",
    noLink: "Bu eğitim için dış link yok",
    weekTitle: "Bu hafta yapman gerekenler",
    weekActiveStep: "Aktif adımın:",
    weekEmpty: "Harika — bu hafta bekleyen bir aksiyon yok.",
    weekContinue: "Devam et",
    weekStart: "Başlamayı unutma",
    weekCongrats: "Tebrikler, tamamladın",
    nextTitle: "Sıradaki önerin",
    microTitle: "Bu haftanın pratikleri",
    microHint: "Zayıf yetkinliklerin için 10–30 dk’lık kısa iş-yaşam pratikleri. Yaklaşık gelişim sinyali — kesin bilimsel ölçüm değil.",
    microEmptyChat: "Önce Kariyer Sohbetini tamamla; zayıf alanlarına özel pratikler burada görünecek.",
    microEmptyWeek: "Bu hafta için henüz pratik yok. Sohbeti yenile veya pazartesi paketini bekle.",
    microDone: "Yaptım",
    microDoneLabel: "Yapıldı",
    microDue: "Öneri gün",
    sectorNotesTitle: "Sektör notların",
    sectorNotesHint: "3–5 dakikalık mentör notları — blog değil, üründe kısa rehberlik. Maaş veya tarih garantisi içermez.",
    sectorNotesEmpty: "Sohbette hedef sektörünü yazınca burada ilgili notlar görünür. Eşleşmezse genel kariyer notları gelir.",
    sectorNotesSector: (key) => (key === "genel" ? "Genel kariyer" : ("Sektör: " + key)),
    sectorCta: {
      micro_task: "İlgili pratiğe git",
      chat: "Sohbete dön",
      training: "Eğitime git",
    },
    draftResumeTitle: "Yarıda kalan sohbetin var",
    draftResumeLink: "Devam et",
    remindersTitle: "Haftalık e-posta hatırlatması",
    remindersHint: "Yol haritan, eğitimlerin ve pratiklerin için haftada en fazla bir özet mail. Varsayılan kapalı.",
    remindersOn: "Açık",
    remindersOff: "Kapalı",
    startedAt: "Başlangıç",
    completedAt: "Bitiş",
    loading: "Yükleniyor…",
    notConfigured: "Supabase yapılandırması eksik. Ortam değişkenlerini kontrol et.",
  },
  en: {
    brand: "Career Pick",
    title: "My learning plan",
    subtitle: "Follow your roadmap to your goal — start and finish courses.",
    loginPrompt: "Sign in with Gmail to see your learning plan.",
    loginBtn: "Sign in with Gmail",
    logoutBtn: "Sign out",
    chatBtn: "Career Chat",
    jobFitBtn: "Job fit",
    overall: "Overall progress",
    empty: "No recommended trainings yet. Complete Career Chat.",
    goalTitle: "Your career goal",
    compareSummaryTitle: "Competency progress",
    compareSummaryText: (up, down) =>
      `Progress signal in ${up} area(s); a softer signal in ${down}. Approximate comparison only.`,
    compareSummaryNone: "No comparison yet. Complete Career Chat a second time to see a summary here.",
    compareSummaryFirst: "First measurement saved. Comparison unlocks on the second chat.",
    roadmapTitle: "Your roadmap",
    stepProgress: "Step",
    stepStatus: {
      bekliyor: "Waiting",
      aktif: "Active",
      bitti: "Done",
    },
    noResources: "No resources yet",
    otherTrainings: "Other courses",
    status: {
      tamamlandi: "Completed",
      devam_ediyor: "In progress",
      eksik: "Not started",
    },
    openTraining: "Open course",
    markStarted: "I started",
    markCompleted: "I finished",
    noLink: "No external link for this course",
    weekTitle: "This week’s actions",
    weekActiveStep: "Your active step:",
    weekEmpty: "Nice — nothing waiting this week.",
    weekContinue: "Keep going",
    weekStart: "Don’t forget to start",
    weekCongrats: "Congrats, you finished",
    nextTitle: "Up next",
    microTitle: "This week’s practices",
    microHint: "Short 10–30 min work-life drills for weaker competencies. An approximate growth signal — not a scientific measurement.",
    microEmptyChat: "Complete Career Chat first; practices for your weaker areas will show up here.",
    microEmptyWeek: "No practices for this week yet. Re-run chat or wait for Monday’s pack.",
    microDone: "Done",
    microDoneLabel: "Completed",
    microDue: "Suggested day",
    sectorNotesTitle: "Your sector notes",
    sectorNotesHint: "3–5 minute mentor notes — in-product guidance, not a blog. No salary or date guarantees.",
    sectorNotesEmpty: "After you name a target sector in chat, matching notes appear here. Unknown sectors get general career notes.",
    sectorNotesSector: (key) => (key === "genel" ? "General career" : ("Sector: " + key)),
    sectorCta: {
      micro_task: "Go to related practice",
      chat: "Back to chat",
      training: "Go to courses",
    },
    draftResumeTitle: "You have an unfinished chat",
    draftResumeLink: "Continue",
    remindersTitle: "Weekly email reminders",
    remindersHint: "At most one digest per week about your roadmap, courses, and practices. Off by default.",
    remindersOn: "On",
    remindersOff: "Off",
    startedAt: "Started",
    completedAt: "Completed",
    loading: "Loading…",
    notConfigured: "Supabase is not configured. Check environment variables.",
  },
};
